### PR TITLE
chore: upgrade stencil and node

### PR DESCRIPTION
**Pull request by ju-Skinner**
# Description

Upgrade Stencil to the latest version. Based on the requirements of Stencil v4, it was required to use the Node v18.19, since we have been testing 20 and things have been running well. I elected to use this opportunity to move to Node v20.5.0

# How to Test
In the root directory, run the following commands
1. `rm -rf **/node_modules`. This will remove all the node_modules in the subdirectories
2.  If you are using `nvm`, run `nvm install 20.5.0`
3. `nvm use`
4. `yarn install`
5. Start the server, `yarn start`... or however you would if you use Tmux

Things should start as normal. In another terminal window, confirm there are no Git changes.

### CODE REVIEW

**Review by anechol — APPROVED** [review]
Followed all steps and ran into zero issues. No git changes in the terminal, though.

**Review by pixelflips — COMMENTED** [review]
Not entirely sure if they're related or not, but seeing a few linting errors. Can you confirm?

**Comment by ju-Skinner** [comment]
> Not entirely sure if they're related or not, but seeing a few linting errors. Can you confirm?

Yes, I mentioned those in my last standup. They'll be resolved prior to merging.

**Review by pixelflips — APPROVED** [review]
🔥 LGTM!

**Review by pixelflips — APPROVED** [review]
Ran through commands as instructed and all is still working well! LGTM! 👍🏼

**Review by QuintonJason — APPROVED** [review]
Went through the instructions with no issues. Click around and had no issues. Great work 🏆

**Review by anechol — APPROVED** [review]

**Review by anechol — APPROVED** [review]

**Review by pixelflips — APPROVED** [review]
No issues or concerns here. LGTM! 👍🏼 - great work!

**Pull request merged**
